### ISSUE TITLE
Nonexistent "Development Notes"

### ISSUE THREAD

**Issue by dmoruzzi** [CitiesSkylinesMultiplayer/Website#2]
The website's navigation header redirects to CMS's [Development-Notes](https://github.com/CitiesSkylinesMultiplayer/CSM/wiki/Development-Notes)'s wiki. 

https://github.com/CitiesSkylinesMultiplayer/Website/blob/a8f9ae6874e53cd03cd2e96d3022ff6dcdd843fc/src/components/App.tsx#L94-L99

However, this page does not exist. Additionally, there is no [_history](https://github.com/CitiesSkylinesMultiplayer/CSM/wiki/Development-Notes/_history) of this page.

**Comment by DominicMaas** [comment]
Interesting, not sure when this broke. What I may do is update the wiki to create a Development Notes page that links to the sub-developer notes resources. 

Will come back to this either later today, or during the weekend.

**Comment by DominicMaas** [comment]
Okay, I've updated the website, just removed the link as you can easily find the notes by looking at the wiki. Thanks for the heads-up though!
